export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const searchConstants = {
  IS_SEARCH_BAR_FOCUSED: "IS_SEARCH_BAR_FOCUSED",
  SEARCHTERM_LENGTH_COUNT: "SEARCHTERM_LENGTH_COUNT",
};

export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
};
export const serviceConstants = {
  GET_SERVICE_REQUEST: "GET_SERVICE_REQUEST",
  GET_SERVICE_FAILURE: "GET_SERVICE_FAILURE",
  GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",
  ADD_SERVICE_REQUEST: "ADD_SERVICE_REQUEST",
  ADD_SERVICE_FAILURE: "ADD_SERVICE_FAILURE",
  ADD_SERVICE_SUCCESS: "ADD_SERVICE_SUCCESS",
  UPDATE_SERVICE_REQUEST: "UPDATE_SERVICE_REQUEST",
  UPDATE_SERVICE_FAILURE: "UPDATE_SERVICE_FAILURE",
  UPDATE_SERVICE_SUCCESS: "UPDATE_SERVICE_SUCCESS",
};
export const contactConstants = {
  GET_CONTACT_REQUEST: "GET_CONTACT_REQUEST",
  GET_CONTACT_FAILURE: "GET_CONTACT_FAILURE",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
};

export const partnershipConstants = {
  GET_PARTNERSHIP_REQUEST: "GET_PARTNERSHIP_REQUEST",
  GET_PARTNERSHIP_FAILURE: "GET_PARTNERSHIP_FAILURE",
  GET_PARTNERSHIP_SUCCESS: "GET_PARTNERSHIP_SUCCESS",
  ADD_PARTNERSHIP_REQUEST: "ADD_PARTNERSHIP_REQUEST",
  ADD_PARTNERSHIP_FAILURE: "ADD_PARTNERSHIP_FAILURE",
  ADD_PARTNERSHIP_SUCCESS: "ADD_PARTNERSHIP_SUCCESS",
  UPDATE_PARTNERSHIP_REQUEST: "UPDATE_PARTNERSHIP_REQUEST",
  UPDATE_PARTNERSHIP_FAILURE: "UPDATE_PARTNERSHIP_FAILURE",
  UPDATE_PARTNERSHIP_SUCCESS: "UPDATE_PARTNERSHIP_SUCCESS",
};

export const blogConstants = {
  GET_BLOG_REQUEST: "GET_BLOG_REQUEST",
  GET_BLOG_FAILURE: "GET_BLOG_FAILURE",
  GET_BLOG_SUCCESS: "GET_BLOG_SUCCESS",
  ADD_BLOG_REQUEST: "ADD_BLOG_REQUEST",
  ADD_BLOG_FAILURE: "ADD_BLOG_FAILURE",
  ADD_BLOG_SUCCESS: "ADD_BLOG_SUCCESS",
  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
};

export const projectConstants = {
  ADD_PROJECT_REQUEST: "ADD_PROJECT_REQUEST",
  ADD_PROJECT_FAILURE: "ADD_PROJECT_FAILURE",
  ADD_PROJECT_SUCCESS: "ADD_PROJECT_SUCCESS",
  GET_PROJECT_REQUEST: "GET_PROJECT_REQUEST",
  GET_PROJECT_FAILURE: "GET_PROJECT_FAILURE",
  GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",
  GET_PROJECT_BY_SLUG_REQUEST: "GET_PROJECT_BY_SLUG_REQUEST",
  GET_PROJECT_BY_SLUG_FAILURE: "GET_PROJECT_BY_SLUG_FAILURE",
  GET_PROJECT_BY_SLUG_SUCCESS: "GET_PROJECT_BY_SLUG_SUCCESS",
  GET_PROJECT_BY_ID_REQUEST: "GET_PROJECT_BY_ID_REQUEST",
  GET_PROJECT_BY_ID_FAILURE: "GET_PROJECT_BY_ID_FAILURE",
  GET_PROJECT_BY_ID_SUCCESS: "GET_PROJECT_BY_ID_SUCCESS",
  GET_PROJECT_BY_NAME_REQUEST: "GET_PROJECT_BY_NAME_REQUEST",
  GET_PROJECT_BY_NAME_FAILURE: "GET_PROJECT_BY_NAME_FAILURE",
  GET_PROJECT_BY_NAME_SUCCESS: "GET_PROJECT_BY_NAME_SUCCESS",
};

export const initDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",
};

export const resetConstants = {
  RESET_PROJECT_DETAILS: "RESET_PROJECT_DETAILS",
  RESET_SEARCHED_PROJECTS: "RESET_SEARCHED_PROJECTS",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",
  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",

  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};
